#+PROPERTY: header-args :tangle yes

* Figure out if we're at work or home

#+begin_src emacs-lisp
  (message "Starting up org-mode init file")
  (setq is-linux (and (getenv "DISPLAY") (if (string= system-type "gnu/linux") t nil)))
  (setq my-org-files (list "~/init/org/Capture.org.gpg" "~/init/org/other.org.gpg" "~/init/org/home.org.gpg" "~/init/org/vec.org.gpg" "~/init/org/journal.org.gpg"))
  ;; Exclude if at work
  (setq my-org-files (if (file-directory-p "/home/kofoed") (remove "~/init/org/other.org.gpg" my-org-files) my-org-files))
#+end_src

#+RESULTS:
| ~/init/org/Capture.org.gpg | ~/init/org/home.org.gpg | ~/init/org/vec.org.gpg | ~/init/org/journal.org.gpg |

* Setting up ELPA package system

Here we need some locally downloaded stuff, like all-icons (to be
replaced by nerd-icons?)

There are version issues around v26/27 versus gpg keys. These are
needed for downloading packages, and have recently (3-4 years)
expired, so recent emacs versions may not have the most recent keys.

The algorithm priority is a workaround.

For package-check-signature, 'allow-unsigned is the default, but this
does not always work.

#+begin_src emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/lisp") ; NOTE My local lisps
  (add-to-list 'load-path "~/src/all-the-icons-dired") ; NOTE My local lisps

  (require 'package)

  (when (< emacs-major-version 27)
    (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")         ; NOTE w/o creates no "gnu", just gnupg
    (require 'gnu-elpa-keyring-update)                             ; NOTE Now accepts gnu archives
    (add-to-list 'package-archives '("nongnu" . "http://elpa.nongnu.org/nongnu/") t))

  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (setq package-check-signature nil)

  (package-initialize)
#+end_src

Find a way to refresh only when its a week since last time
How about creating a file inside elpa, and do (f-touch) on this every refresh?

#+begin_src emacs-lisp
  (package-refresh-contents) nil)
#+end_src

Will use use-package, apparently "straight" is an alternative to this.
:ensure t is absolutely required, but can be made global.

#+begin_src emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (setq use-package-always-ensure t)
#+end_src

* Installing packages
** Presentation fonts/colors/tabs/themes
*** Installing a theme collection

Using goldenrod as default for now, selecting some with C-c h via
hydra. other collections seem to be available.

#+begin_src emacs-lisp
  (use-package color-theme-modern
    :config
    (load-theme 'goldenrod t t)
    (enable-theme 'goldenrod))
#+end_src

#+RESULTS:
: t

*** Select tab system - centaur on newer emacs versions

Choose tabbar (built-in) or centaur tab, dependent on emacs version.

#+begin_src emacs-lisp
  (if (< emacs-major-version 27)
      (use-package tabbar
        :config (tabbar-mode)
        (set-face-attribute 'tabbar-default    nil :background "gray60")
        (set-face-attribute 'tabbar-unselected nil :background "gray85"  :foreground "gray30" :box nil)
        (set-face-attribute 'tabbar-selected   nil :background "yellow" :foreground "blue"  :box nil :weight 'bold)
        (set-face-attribute 'tabbar-button     nil :box '(:line-width 1 :color "gray72" :style released-button))
        (set-face-attribute 'tabbar-separator  nil :height 0.7)))
#+end_src

#+RESULTS:
: t

Use centaur tabs when version is 27 or newer

#+begin_src emacs-lisp
  (if (> emacs-major-version 26)
      (use-package centaur-tabs
        :demand
        :config
        (centaur-tabs-mode t)
                                          ;(setq centaur-tabs-height 32) ; Does not affect font or icon
                                          ;(centaur-tabs-headline-match)
                                          ;(setq centaur-tabs-style "bar")
        (setq centaur-tabs-set-bar 'over)
                                          ;(centaur-tabs-change-fonts "arial" 160) 
        (setq centaur-tabs-set-icons t)
        (setq centaur-tabs-icon-type 'all-the-icons)
                                          ;(setq centaur-tabs-plain-icons t) ; Replacing icons!
                                          ;(setq centaur-tabs-modified-marker t)
        (defun centaur-tabs-buffer-groups ()
          "Use as few groups as possible."
          (list (cond ((string-equal "*" (substring (buffer-name) 0 1))
                       (cond ((string-equal "eglot" (downcase (substring (buffer-name) 1 6)))
                              "Eglot")
                             (t
                              "Tools")))
                      ((string-equal "magit" (downcase (substring (buffer-name) 0 5)))
                       "Magit")
                      (t
                       "Default"))))
        (centaur-tabs-group-by-projectile-project);KLUDGE This is actually a bugfix
        :bind
        ("C-<left>" . centaur-tabs-backward)
        ("C-<right>" . centaur-tabs-forward)))
#+end_src

#+RESULTS:

*** install icons for use in org, modelines, and tabs

Download all the icons package, this requires to run
"all-the-icons-install-fonts" via M-x after. This is potentially
replaced now by nerd-icons.

nerd-icons: As for all-icons above, M-x
nerd-icons-install-fonts is required.

#+begin_src emacs-lisp
  (use-package all-the-icons
      :if (display-graphic-p))
  (load "all-the-icons-dired")
  (add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
  (use-package nerd-icons)
#+end_src

#+RESULTS:
: t

*** Modeline selection and dimmer mode

Dimming the non-active windows may be useful, 20% is default

#+begin_src emacs-lisp
  (use-package dimmer
    :config
    (dimmer-configure-which-key)
    (dimmer-configure-helm)
    (setq dimmer-fraction 0.3)
    (dimmer-mode t))
#+end_src

#+RESULTS:
: t

Using doom-modeline. Other modelines are available, like powerline and
spacemacs.

#+begin_src emacs-lisp
  (use-package doom-modeline
    :init (doom-modeline-mode 1))
#+end_src

#+RESULTS:
: t

** Shell and programming

Using *eat* as main shell for now, works reasonably well, and seems to
be a better term emulator than ansi-term. Treemacs makes projects
easier.

#+begin_src emacs-lisp
  (use-package cider)
  (use-package eat
    :config
    (define-key eat-semi-char-mode-map (kbd "M-o") 'ace-window)
    (define-key eat-semi-char-mode-map (kbd "M-0") 'treemacs-select-window))
  (define-key eat-semi-char-mode-map (kbd "M-a") (lambda () (interactive) (switch-to-buffer "*Org Agenda*")))
  (add-hook 'window-configuration-change-hook
            (lambda ()
              (when (string-equal major-mode "eat-mode")
                (unless (bound-and-true-p called-once)
                                          ;(eat-term-send-string eat-terminal "exec $SHELL -l")
                  (eat-term-send-string eat-terminal "if [[ \"$(hostname)\" == \"dsc005\" ]];then ssh dsc001;fi")
                  (eat-self-input 1 'return)
                  (setq-local called-once t)))))
#+end_src

#+RESULTS:
| (lambda nil (when (string-equal major-mode eat-mode) (unless (bound-and-true-p called-once) (eat-term-send-string eat-terminal if [[ "$(hostname)" == "dsc005" ]];then ssh dsc001;fi) (eat-self-input 1 (quote return)) (setq-local called-once t)))) | dimmer-config-change-handler | window--adjust-process-windows |

Project management

Using treemacs for now. Apparently a package called projectile might be useful.

#+begin_src emacs-lisp
  (use-package treemacs
    :bind (("M-0" . treemacs-select-window)
           ("M-o" . ace-window)))
#+end_src

#+RESULTS:
: ace-window

** Movement and selection

Using helm to select commands and buffers etc.Can't get helm
find-files to work properly, so back to normal for that.

tab-bar etc -> this is undefined for some reason, hence setting it to
nil in :init

Avy mode has some other options, like char-1

#+begin_src emacs-lisp
    (use-package helm
      :init (setq tab-bar-tab-name-function nil)
      :bind
      (("M-x"     . helm-M-x)
       ("M-y"     . helm-show-kill-ring)
       ("C-x C-b" . helm-mini)
      ;("C-x C-f" . helm-find-files)
       ("M-i"     . helm-swoop)
       ("M-s o"   . helm-occur)))

  (global-set-key (kbd "C-x C-f") 'ido-find-file)

  (use-package avy
    :bind
    (("C-:" . 'avy-goto-char-2)))
#+end_src

#+RESULTS:
: avy-goto-char-2

** Coloring of keywords and marking random text + fic

Fic-mode should work everywhere, hightlight actions and FIXME
etc. Markerpen is manually downloaded.

#+begin_src emacs-lisp
  (require 'markerpen)

  (use-package fic-mode :ensure t)
  (setq p-modes '(tcl-mode-hook ruby-mode-hook perl-mode-hook cperl-mode-hook emacs-lisp-mode-hook python-mode-hook))
  (mapcar (lambda (mode) (add-hook mode 'fic-mode)) p-modes)
  (setq fic-highlighted-words '("FIXME" "TODO" "NOTE" "KLUDGE" "BUG"))
#+end_src

#+RESULTS:
| FIXME | TODO | NOTE | KLUDGE | BUG |

** Org mode setup (and org-babel)
*** Main setup

Perhaps use :bind to improve readability below?

#+begin_src emacs-lisp
  (use-package org
    :pin gnu
    :config
    (setq org-log-done 'time)
    (setq org-return-follows-link t)
    (add-hook 'org-mode-hook 'org-indent-mode)
    (add-hook 'org-mode-hook 'hl-line-mode)
    (add-hook 'org-agenda-mode-hook 'hl-line-mode)
    (define-key org-mode-map (kbd "C-c <up>") 'org-priority-up)
    (define-key org-mode-map (kbd "C-c <down>") 'org-priority-down)
    (define-key global-map "\C-cl" 'org-store-link)
    (define-key global-map "\C-ca" 'org-agenda)
    (define-key global-map "\C-cc" 'org-capture)
    ;(setq org-directory "~/init/org")
    (setq org-default-notes-file "~/init/org/Capture.org.gpg")
    (setq org-agenda-files my-org-files)
    (define-key org-mode-map (kbd "C-c C-g C-r") 'org-shiftmetaright)
    (setq org-hide-emphasis-markers t)
    (setq org-agenda-window-setup 'current-window)
    (setq org-agenda-restore-windows-after-quit t)
    (setq org-agenda-skip-scheduled-if-done t)
    ;(setq org-agenda-skip-function-global '(org-agenda-skip-entry-if 'todo 'done))
    )
  (setq org-refile-targets '((nil :maxlevel . 9)
                             (org-agenda-files :maxlevel . 9)))
  (setq org-todo-keywords
        '((sequence "TODO" "WAIT" "|" "CANCELLED" "DONE")))
#+end_src

#+RESULTS:
| sequence | TODO | WAIT |   |   | CANCELLED | DONE |

*** Babel setup - various programming languages inside org mode

We change the default of asking to execute w/C-c C-c
It seems the ob-tcl does not exist, as it should?

#+begin_src emacs-lisp
  (require 'ob-clojure)
  (require 'ob-ruby)
  (require 'ob-shell)
  (require 'ob-tcl)
  (setq org-babel-clojure-backend 'cider)
  (setq org-confirm-babel-evaluate nil)
#+end_src

#+RESULTS:

*** Bullets and fonts for headlines

  Here follows setup with coloring and bullets for orgmode. Not sure yet about the fonts and their sizes.

 #+begin_src emacs-lisp
   (use-package org-bullets
     :config
     (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
   (font-lock-add-keywords 'org-mode
                           '(("^ +\\([-*]\\) "
                              (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
   (when window-system
     (let* ((variable-tuple (cond ((x-list-fonts "Source Sans Pro") '(:font "Source Sans Pro"))
                                  ((x-list-fonts "Lucida Grande")   '(:font "Lucida Grande"))
                                  ((x-list-fonts "Verdana")         '(:font "Verdana"))
                                  ((x-family-fonts "Sans Serif")    '(:family "Sans Serif"))
                                  (nil (warn "Cannot find a Sans Serif Font.  Install Source Sans Pro."))))
            (base-font-color     (face-foreground 'default nil 'default))
            (headline           `(:inherit default :weight bold :foreground ,base-font-color)))
       (custom-theme-set-faces 'user
                               `(org-level-8 ((t (,@headline ,@variable-tuple))))
                               `(org-level-7 ((t (,@headline ,@variable-tuple))))
                               `(org-level-6 ((t (,@headline ,@variable-tuple))))
                               `(org-level-5 ((t (,@headline ,@variable-tuple))))
                               `(org-level-4 ((t (,@headline ,@variable-tuple :height 1.1))))
                               `(org-level-3 ((t (,@headline ,@variable-tuple :height 1.2))))
                               `(org-level-2 ((t (,@headline ,@variable-tuple :height 1.3))))
                               `(org-level-1 ((t (,@headline ,@variable-tuple :height 1.4))))
                               `(org-document-title ((t (,@headline ,@variable-tuple :height 1.5 :underline nil)))))))
#+end_src

#+RESULTS:

*** Setup of org templates (C-c c), creating actions distributed across multiple files

Here are templates for capturing tasks for December 2024, focused on VEC project at work

#+begin_src emacs-lisp
  (setq outline-minor-mode-cycle t)

  (setq org-capture-templates
        '(("t" "General task"       entry (file+regexp org-default-notes-file "Tasks") "* TODO %?\n  %i\n  %a")
          ("c" "C2C task"           entry (file+headline "~/init/org/vec.org.gpg" "C2C tasks" ) "* TODO %?\n  %i\n  %a")
          ("p" "PCIE task"          entry (file+headline "~/init/org/vec.org.gpg" "PCIE tasks") "* TODO %?\n  %i\n  %a")
          ("v" "VEC top-level task" entry (file+regexp "~/init/org/vec.org.gpg" "VEC Top.*" ) "* TODO %?\n  %i\n  %a")
          ("e" "Emacs task"         entry (file+headline "~/init/org/home.org.gpg" "Emacs Tasks") "* TODO %?\n  %i\n  %a")
          ("l" "Clojure task"       entry (file+headline "~/init/org/home.org.gpg" "Clojure Tasks") "* TODO %?\n  %i\n  %a")
          ("j" "Journal"            entry (file+datetree "~/init/org/journal.org.gpg")
           "* %?\nEntered on %U\n%i\n  %a")))

  (setq org-agenda-custom-commands
        '(("u" "Untagged tasks" tags-todo "-{.*}")))
  ;	("d" "Daily Agenda"
  ;	 ((agenda "" ((org-agenda-span 'day)
  ;		      (org-deadline-warning-days 7)))))))
#+end_src

#+RESULTS:
| u | Untagged tasks | tags-todo | -{.*} |

*** Org subtasks and helm-org

Procedure for inserting sub-task , have not really used this yet

#+begin_src emacs-lisp
  (defun my-org-insert-sub-task ()
    (interactive)
    (let ((parent-deadline (org-get-deadline-time nil)))
      (org-goto-sibling)
      (org-insert-todo-subheading t)
      (when parent-deadline
        (org-deadline nil parent-deadline))))
  (define-key org-mode-map (kbd "C-c s") 'my-org-insert-sub-task)
#+end_src

#+RESULTS:
: my-org-insert-sub-task

The helm-org below I've not got to work yet, not sure what it does !

#+begin_src emacs-lisp
      (use-package helm-org
        ;:config
        ;(add-to-list 'helm-completing-read-handlers-alist '(org-capture . helm-org-completing-read-tags))
        ;(add-to-list 'helm-completing-read-handlers-alist '(org-set-tags . helm-org-completing-read-tags))
        )
      (add-hook 'helm-mode-hook
                (lambda ()
                  (add-to-list 'helm-completing-read-handlers-alist '(org-capture . helm-org-completing-read-tags))
                  (add-to-list 'helm-completing-read-handlers-alist '(org-set-tags . helm-org-completing-read-tags))))
#+end_src

#+RESULTS:
| lambda | nil | (add-to-list (quote helm-completing-read-handlers-alist) (quote (org-capture . helm-org-completing-read-tags))) | (add-to-list (quote helm-completing-read-handlers-alist) (quote (org-set-tags . helm-org-completing-read-tags))) |

** Hydra mode setup for keybinding selections

Hydra allows a menu for a key or keyseq. bind-key has not really been used yet.

*** Installing hydra, M-SPC works?

#+begin_src emacs-lisp
  (use-package bind-key)
  (use-package major-mode-hydra
    :bind
    ("M-SPC" . major-mode-hydra)) ;Can we make this key work?
#+end_src

#+RESULTS:
: major-mode-hydra

*** Hydra selectors for themes, toggle modes, shell, cider

#+begin_src emacs-lisp
  (setq good-themes
        '(goldenrod classic cobalt dark-blue2 desert digital-ofs1 euphoria feng-shui fischmeister
                    late-night lawrence ld-dark lethe marquardt retro-green xemacs tango-dark))

  (defun ek-theme (theme) (interactive) (mapcar #'disable-theme custom-enabled-themes) (load-theme theme t t) (enable-theme theme))

  (defhydra hydra-appearance (:color blue)
    ("1" (ek-theme 'wheat)             "wheat"             :column "Theme")
    ("2" (ek-theme 'goldenrod)         "goldenrod"         :column "Theme")
    ("3" (ek-theme 'classic)           "classic"           :column "Theme")
    ("4" (ek-theme 'cobalt)            "cobalt"            :column "Theme")
    ("5" (ek-theme 'feng-shui)         "feng-shui"         :column "Theme")
    ("6" (ek-theme 'late-night)        "late-night"        :column "Theme")
    ("7" (ek-theme 'retro-green)       "retro-green"       :column "Theme")
    ("8" (ek-theme 'word-perfect)      "word-perfect"      :column "Theme")
    ("9" (ek-theme 'taming-mr-arneson) "taming-mr-arneson" :column "Theme")
    ("0" (ek-theme 'light-blue)        "light-blue       " :column "Theme")

    ("l" display-line-numbers-mode "line-numbers"   :column "Toggle")
    ("c" column-number-mode        "columns"        :column "Toggle")
    ("g" hl-line-mode              "hl-line"        :column "Toggle")
    ("G" global-hl-line-mode       "hl-line GLOBAL" :column "Toggle")
    ("t" toggle-truncate-lines     "truncate"       :column "Toggle")
    ("f" follow-mode               "follow"         :column "Toggle")
    ("v" visual-line-mode          "visual-line"    :column "Toggle")
    ("w" whitespace-mode           "whitespace"     :column "Toggle")

    ("m" helm-all-mark-rings       "mark-rings"     :column "Helm")
    ("r" helm-register             "registers"      :column "Helm")
    ("p" helm-top                  "top"            :column "Helm")
    ("o" helm-colors               "Pick color"     :column "Helm")

    ("q" nil                       "Quit menu" :color red :column nil))
  (global-set-key (kbd "C-c h") 'hydra-appearance/body)

#+end_src

#+RESULTS:
: hydra-appearance/body

*** Hydra for lisp modes, emacs-lisp and clojure

For these two hydras, M-SPC is the key (does it work though?)

#+begin_src emacs-lisp

  (major-mode-hydra-define emacs-lisp-mode nil
    ("Eval"
     (("b" eval-buffer "buffer")
      ("e" eval-defun "defun")
      ("r" eval-region "region")
      ("q" nil "quit"))
     "REPL"
     (("I" ielm "ielm"))
     "Test"
     (("t" ert "prompt")
      ("T" (ert t) "all")
      ("F" (ert :failed) "failed"))
     "Doc"
     (("d" describe-foo-at-point "thing-at-pt")
      ("f" describe-function "function")
      ("v" describe-variable "variable")
      ("i" info-lookup-symbol "info lookup"))))
#+end_src

#+RESULTS:
: major-mode-hydras/emacs-lisp-mode/body

Connect buffer to server is for example for bb --nrepl-server

#+begin_src emacs-lisp
  (major-mode-hydra-define clojure-mode nil
    ("Connect"
     (("j" cider-jack-in      "jack-in")
      ("J" cider-jack-in-cljs "jack-in-cljs")
      ("c" cider-connect      "Connect buffer to server")
      ("R" nil "TBD reconnect")
      ("Q" nil "TBD disconnect")
      ("q" nil "quit"))))

#+end_src

#+RESULTS:
: major-mode-hydras/clojure-mode/body

*** Hydra for shell and markerpen

#+begin_src emacs-lisp

  (defhydra hydra-shell-stuff (:color blue)
    "Shells"
    ("s" shell                   "shell")
    ("a" (ansi-term "/bin/bash") "ansi-term")
    ("e" (eat "/bin/bash" "echo hi") "eat-term")
    ("r" rename-buffer           "Rename buffer"))
  (global-set-key [f2] 'hydra-shell-stuff/body)

  (global-set-key (kbd "C-'") 'erase-buffer)
  (global-set-key (kbd "C-x r p") 'replace-rectangle)

  (defhydra hydra-comma (:color blue)
    "Toggle"
    ("m" markerpen-mark-region      "mark region")
    ("c" markerpen-clear-all-marks  "clear all marks")
    ("r" (markerpen-mark-region 1)  "red")
    ("g" (markerpen-mark-region 2)  "grey")
    ("y" (markerpen-mark-region 3)  "yellow")
    ("b" (markerpen-mark-region 4)  "blue")
    ("u" (markerpen-mark-region 5)  "underline"))
  (global-set-key (kbd "C-,") 'hydra-comma/body)
#+end_src

#+RESULTS:
: hydra-comma/body

* Other settings
** Various toggle settings

#+begin_src emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)

  (winner-mode 1)				;Allows revert windows content/position history w/ C-c <|> 
  (ffap-bindings)				;ffap = fINDfILEaTPoint
  (setq visible-bell t)
  (tool-bar-mode -1)
  ;(scroll-bar-mode -1)

  (global-hi-lock-mode 1)
  (show-paren-mode t)
  (put 'erase-buffer 'disabled nil)
  (put 'narrow-to-region 'disabled nil)
#+end_src

#+RESULTS:

** Emacs shell setup

#+begin_src emacs-lisp
  (autoload 'ansi-color-for-comint-mode-on "ansi-color" nil t)
  (add-hook 'shell-mode-hook 'ansi-color-for-comint-mode-on)
  (add-hook 'shell-mode-hook (lambda () (face-remap-set-base 'comint-highlight-prompt :inherit nil)))

  (setq display-buffer-alist '(("\\`\\*e?shell" display-buffer-same-window)))

  (setq ansi-color-names-vector
        ["black" "tomato" "PaleGreen2" "gold1"
         "DeepSkyBlue1" "MediumOrchid1" "cyan" "white"])
  (setq ansi-color-names-vector
        ["black" "tomato" "PaleGreen2" "gold1"
         "blue" "MediumOrchid1" "cyan" "white"])
  ;; NOTE Fix ansi-term keys we want(!)
  (add-hook 'term-mode-hook (lambda () (define-key term-raw-map (kbd "M-o") 'ace-window)))
  (add-hook 'term-mode-hook (lambda () (define-key term-raw-map (kbd "M-0") 'treemacs-select-window)))
  (add-hook 'term-mode-hook (lambda () (define-key term-raw-map (kbd "M-x") 'helm-M-x)))

#+end_src

#+RESULTS:
| lambda | nil | (define-key term-raw-map (kbd M-x) (quote helm-M-x))               |
| lambda | nil | (define-key term-raw-map (kbd M-0) (quote treemacs-select-window)) |
| lambda | nil | (define-key term-raw-map (kbd M-o) (quote ace-window))             |

** Other functions like ek-set mode and inital text size


Below mode is intended to be used to highlight interesting stuff in innovus/etc log files

#+begin_src emacs-lisp
  (defun ek-hi-set ()
    (interactive)
    (hi-lock-mode -1)
    (hi-lock-mode)
    (highlight-lines-matching-regexp "^\\(**WARN:\\).*$" 'hi-green-b)
    ;(highlight-lines-matching-regexp "^\\(#WARNING\\).*$" 'hi-red-b)
    (highlight-lines-matching-regexp "^\\(**ERR\\).*$" 'hi-red-b)
    )
  (global-set-key (kbd "<f5>") 'ek-hi-set)

#+end_src

#+RESULTS:
: ek-hi-set

Setup text resolution based on what we can figure out about the current system.

#+begin_src emacs-lisp

  ;; Get screen info if on X
  (if is-linux
      ;;(if (= (string-to-number (getenv "SHLVL")) 3) ;; TODO test instead for existence of X and command below
      (progn
        (setq dimensions (shell-command-to-string "xdpyinfo | grep dimension"))
        (string-match "\\([0-9]+\\)x\\([0-9]+\\) pixels (\\([0-9]+\\)x\\([0-9]+\\)" dimensions)
        (setq width  (string-to-number (match-string 1 dimensions)))
        (setq height (string-to-number (match-string 2 dimensions)))
        )
    (progn
      (setq width  1920)
      (setq height 1080)))

                                          ; Set according to screen resolution
  (cond ((> height 1590) (set-face-attribute 'default nil :height 120))
        ((= height 1080) (set-face-attribute 'default nil :height 60))
        (t nil))
#+end_src

#+RESULTS:

* Testing stuff and temporary commands/keys

Candidates for keys are

| Key | Default            |
| M-t | transpose words    |
| M-a | backward sentrence |
| M-p | undefined          |
| M-r | move to top/bottom |

** Check centaur buffer type


#+begin_src emacs-lisp
  (defun my/check-buffer-group ()
    "Show what type of centaur buffer this is"
    (interactive)
    (message (car (centaur-tabs-buffer-groups))))
  (global-set-key (kbd "M-t") 'my/check-buffer-group)
  (define-key eat-semi-char-mode-map (kbd "M-t") 'my/check-buffer-group)
#+end_src

#+RESULTS:
: my/check-buffer-group

** Test M-a as switch to agenda

#+begin_src emacs-lisp
  (global-set-key (kbd "M-a") (lambda () (interactive) (switch-to-buffer "*Org Agenda*")))
#+end_src

#+RESULTS:
| lambda | nil | (interactive) | (switch-to-buffer *Org Agenda*) |

* End of file
