* VEC project
* Learning tasks
** DONE Learn tasks in org-mode.
CLOSED: [2024-11-21 Thu 11:28] SCHEDULED: <2024-11-20 Wed>
- Practice various types of lists under tasks
- This was M-RET, showing the same symbol at front
** TODO Setup repl for clojurescript inside emacs
SCHEDULED: <2024-11-22 Fri>
** TODO Make sublist of actions for work
SCHEDULED: <2024-11-22 Fri>
** TODO Reorganize github to isolate work-related out
SCHEDULED: <2024-11-22 Fri>
** DONE Make email for Michael B improvements to Flow
CLOSED: [2024-11-21 Thu 17:39] SCHEDULED: <2024-11-21 Thu>
- Gasket -> think about how to transfer files from one step to the next
- Shared memory -> avoid at any and all cost, every new run in a new, clean directory
- Separate technology specific materials out of flow
For example library and MMMC setup at a common location
** DONE Setup hydra bindings for various
CLOSED: [2024-11-21 Thu 18:20] SCHEDULED: <2024-11-21 Thu>
- hs-mode (hide code)
- agenda mode?
- Markerpen - use C-, as multi-choice, multi-color? Instead of F8/9?
** TODO Review markerpen hydra - can we make color auto? More col's?
SCHEDULED: <2024-11-22 Fri>
** TODO Make more org-files?



* Debug notes
** CLK_REF_IN_N on c2c
Serdes inserted in block#1 c2c_chi_asic...
Driven by direct input (no bufs)
phy_clk_ref_in_n is the port name
This is driven by CTS-net on top-level
E=EAST, W=WEST, placed e/w in G1 -> unconnected in PHY_TC
 
